services:
  step-ca:
    environment:
      - DOCKER_STEPCA_INIT=true
      - DOCKER_STEPCA_INIT_NAME=${STEPCA_NAME:? STEPCA_NAME required}
      - DOCKER_STEPCA_INIT_DNS_NAMES=${STEP_CA_DNS:? STEP_CA_DNS required}
      - DOCKER_STEPCA_INIT_PROVISIONER_NAME=${STEP_CA_PROVISIONER:? STEP_CA_PROVISIONER required}
      - DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=true
      - DOCKER_STEPCA_INIT_PASSWORD=${SMALLSTEP_CA_KEY_PASSWORD:? SMALLSTEP_CA_KEY_PASSWORD required for local setup...}
      - DOCKER_STEPCA_INIT_ACME=${STEP_CA_ACME:- true}

    env_file: .env